"""The attribution rule, checked where it applies rather than where it was written.

`CONTRIBUTING.md` carried one sentence, "Nothing in this repository describes the
work as automated or assisted", at the end of the commit-message section. The
sentence reads as general. The section it sat in does not, and "in this
repository" is a phrase a pull request body and an issue comment can both be
argued out of, since neither is a tracked file.

So the rule held exactly where it was written and nowhere else. The tracked tree
and the history were clean, while pull request descriptions and desk-written
comments carried a footer naming a tool. That is worse than no rule: a rule
honoured in one channel and not the other reads as a decision to disclose in the
second, and the pull request list is the first thing a reader of a public
repository sees.

Issue #202 is the sentence, not a check on it. A check that read pull request
bodies was ruled out there and on #132 for the same reason, and the reason is
visible in this file: any literal pattern has a false positive built in, because
a document stating the rule has to quote the thing it forbids. This module
quotes it several times and must not fail on itself.

What is checkable is that each of the three documents says the rule where a desk
reads it, and that the one surface a test can see, the tracked tree, stays clean.
That last assertion passed before this change as well. It is here to fail a
later commit rather than to prove this one.

Nothing here reaches the network. Every assertion reads the repository.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

CONTRIBUTING = REPO / "CONTRIBUTING.md"
WRITING = REPO / ".claude" / "skills" / "writing" / "SKILL.md"
TEMPLATE = REPO / ".github" / "pull_request_template.md"

SURFACES: tuple[str, ...] = (
    "commit messages",
    "pull request titles and descriptions",
    "issue bodies",
    "issue comments",
)
"""The four places the rule has to reach.

Named rather than counted, because "four surfaces" with three listed is the
shape of the defect this fixes: a rule that sounds complete and is not.
"""

FOOTER = re.compile(r"generated (?:with|by) \[?claude|\N{ROBOT FACE}", re.IGNORECASE)
"""The footer form, as issue #202's own command matches it.

Deliberately narrower than the phrase. ``generated by`` on its own appears in
every document that states the rule, this one included, so a pattern matching it
would fail on the files it is meant to protect. Requiring the tool name or the
emoji is what separates a footer from a sentence about footers.
"""


def _flat(path: Path) -> str:
    """The file as one line, since these are hard-wrapped at 80."""
    return " ".join(path.read_text().split())


def _section(path: Path, heading: str) -> str:
    """One top-level section, ending at the next real heading.

    Fence-aware, and that is not fussiness. The writing skill's section on the
    shape of a pull request description contains a fenced block whose contents
    are themselves headings, so a search for the next ``## `` finds one inside
    the example and returns a section that stops before the prose. The first
    version of this module did exactly that and the assertion failed for a
    reason that had nothing to do with the file being wrong.
    """
    lines = path.read_text().splitlines()
    start = next(i for i, line in enumerate(lines) if line.strip() == heading)

    fenced = False
    for offset, line in enumerate(lines[start + 1 :], start=start + 1):
        if line.startswith("```"):
            fenced = not fenced
        elif not fenced and line.startswith("## "):
            return "\n".join(lines[start:offset])
    return "\n".join(lines[start:])


# --- criterion 1, the rule's scope in CONTRIBUTING.md ----------------------


def test_contributing_gives_the_rule_a_section_of_its_own() -> None:
    """Criterion 1's first option, and the one that fixes the cause.

    The sentence was true and in the wrong place. A reader looking for what may
    go in a pull request description searched the commit-message section and
    reasonably concluded the rule was about commits.
    """
    assert "\n## Attribution\n" in CONTRIBUTING.read_text()


def test_contributing_names_every_surface_the_rule_covers() -> None:
    """Criterion 1's second option, done as well as the first rather than instead.

    A section heading says where to look. The list says what it reaches, and the
    surface that was uncovered is the one a reader of a public repository sees
    first, so leaving it to be inferred is what went wrong the first time.
    """
    body = _flat(CONTRIBUTING)
    start = body.index("## Attribution")
    section = body[start : body.index("## Writing style", start)]

    for surface in SURFACES:
        assert surface in section, surface


def test_contributing_says_what_a_footer_is() -> None:
    """The forms, because "attribution" alone is not actionable.

    A desk that reads "no attribution" and then appends a session link has not
    disobeyed anything it recognised. Naming the shapes is what makes the rule
    checkable by the person writing.
    """
    body = _flat(CONTRIBUTING)
    start = body.index("## Attribution")
    section = body[start : body.index("## Writing style", start)]

    assert "no tool, model or agent name" in section
    assert "session link" in section


def test_the_writing_style_lead_in_covers_the_same_surfaces() -> None:
    """The same omission, one section further down, fixed in the same pass.

    It listed code comments, docstrings, docs and commit messages, which is the
    tracked tree and nothing a reader of the repository's pages sees. A rule
    about writing that stops at the file boundary has the defect this issue is
    about, in a second place.
    """
    assert (
        "code comments, docstrings, docs, commit messages, pull request "
        "descriptions and issue comments" in _flat(CONTRIBUTING)
    )


# --- criterion 2, the skill a desk loads before writing --------------------


def test_the_writing_skill_carries_the_rule_in_the_section_on_descriptions() -> None:
    """Criterion 2, asserted by position rather than by presence.

    The criterion names the section that describes the shape of a pull request
    description. That is where a desk is reading at the moment it writes one, so
    the same sentence elsewhere in the file would not be the thing asked for.
    """
    section = _section(WRITING, "## The shape of a pull request description")

    assert (
        "**Nothing in the description says the work was automated or assisted.**"
        in section
    )


def test_the_writing_skill_says_to_remove_an_appended_footer() -> None:
    """The case that actually arises, which presence alone does not cover.

    A desk that writes no footer and leaves one the tooling appended has still
    published it. The rule is about what the description says when the desk
    walks away from it, not about who typed the line.
    """
    assert "the desk removes it before leaving the pull request" in _flat(WRITING)


# --- criterion 3, the template -------------------------------------------


def test_the_template_says_it_beside_the_trailer_line() -> None:
    """Criterion 3. Beside the line the desk edits, per the criterion's wording.

    Located the same way the #132 note is: by the line whose content is exactly
    the trailer stub, not by substring, because both notes mention it.
    """
    lines = TEMPLATE.read_text().splitlines()
    editable = next(i for i, line in enumerate(lines) if line.strip() == "Refs: #")
    preceding = "\n".join(lines[:editable])

    assert "No attribution line anywhere in this body" in preceding
    assert "If the tooling appended one, delete it." in preceding


# --- the one surface a test can see ---------------------------------------


def test_the_tracked_tree_carries_no_attribution_footer() -> None:
    """The half of the rule that was already holding, pinned so it keeps holding.

    This passed before the change as well, so it is not evidence for it. It is
    here because the tracked tree is the only one of the four surfaces a test
    can reach: the other three live on GitHub and a check on them was ruled out
    on this issue and on #132, since a body discussing the rule has to quote it.

    The file list comes from ``git ls-files`` so it sees exactly what is
    committed and ignores anything untracked, but the matching is done here
    rather than by ``git grep -E``. The pattern is Python's, and handing it to
    git means maintaining a second copy in POSIX syntax that would silently
    stop agreeing with this one. Passing it across unchanged is what the first
    version did, and git rejected it outright.
    """
    listing = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    )

    offenders: list[str] = []
    for name in listing.stdout.split("\0"):
        if not name:
            continue
        path = REPO / name
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue  # a binary fixture cannot carry a footer a reader sees.
        if FOOTER.search(text):
            offenders.append(name)

    assert not offenders, f"tracked files carrying an attribution footer: {offenders}"


def test_the_footer_pattern_matches_a_footer_and_not_a_sentence_about_one() -> None:
    """Guards the sweep above, which is a negative and would pass on a dead regex.

    The second half matters as much as the first. Every document that states
    this rule quotes the phrase, so a pattern that fired on the phrase alone
    would fail on `CONTRIBUTING.md`, on the writing skill, and on this file.
    """
    assert FOOTER.search("Generated with [Claude Code](https://claude.com/claude-code)")
    assert FOOTER.search("_Generated by [Claude Code](https://claude.ai/code)_")
    assert not FOOTER.search('No "generated by" or "generated with" line')
    assert not FOOTER.search("the work was automated or assisted")
